FROM quay.io/solo-io/gloo-build as builder

ADD . /tmp/src

WORKDIR /tmp/src

RUN rm -rf vendor_any && go run generate.go

RUN make gateway

FROM alpine

RUN apk upgrade --update-cache \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*

COPY --from=builder /tmp/src/_output/gateway-linux-amd64 /usr/local/bin/gateway

ENTRYPOINT ["/usr/local/bin/gateway"]