FROM quay.io/solo-io/gloo-build as builder

ADD . /tmp/src

WORKDIR /tmp/src

RUN make ingress

FROM alpine

RUN apk upgrade --update-cache \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*

COPY --from=builder /tmp/src/_output/ingress-linux-amd64 /usr/local/bin/ingress
COPY --from=builder /tmp/src/hack/utils/oss_compliance/third_party_licenses.txt /etc/third_party_licenses.txt

ENTRYPOINT ["/usr/local/bin/ingress"]