FROM quay.io/solo-io/gloo-build as builder

ADD . /tmp/src

WORKDIR /tmp/src

RUN make access-logger

FROM alpine

RUN apk upgrade --update-cache \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*

COPY --from=builder /tmp/src/_output/access-logger-linux-amd64 /usr/local/bin/access-logger

ENTRYPOINT ["/usr/local/bin/access-logger"]